"""affiliate_channel.py -- today's aff_type/aff_source for an affiliate,
whatever a given cached row happens to say.

    import os, sys
    sys.path.insert(0, os.path.join(HERE, ".."))
    from affiliate_channel import current_of

aff_type/aff_source are CURRENT properties of the affiliate, but every cached
row froze whatever they said the day that month was pulled. A re-
categorisation at the source never reaches history this way: GetBlue2024 was
re-tagged SEO -> Retargeting in 2025, and without this, a cache read SEO for
every month before that and Retargeting after -- the same affiliate landing
on both sides of every year-on-year comparison depending only on which month
a row happened to come from.

Two files fix that, and are deliberately kept separate:

  ftd-channels/affiliate-map.json   a wholesale snapshot of bi.players_info_mv
                                     for all ~1,300 affiliates, regenerated by
                                     the query in ftd-channels/build_ftd_channels.py's
                                     own header. Anything hand-edited into it
                                     is destroyed on the next refresh.

  affiliate-overrides.json          hand-maintained corrections for affiliates
                                     we know are mis-tagged AT SOURCE (the map
                                     is a faithful snapshot, which means it is
                                     also faithful to the source's mistakes).
                                     Layered on top of the snapshot, survives a
                                     refresh. See that file's own header.

This exists because current_of() used to live only in build_ftd_channels.py,
which meant every OTHER builder that buckets by aff_source read each row's
own frozen value -- the same "nine copies of one rule" problem carveout.py
solved for the whale exclusion list, just for affiliate categorisation
instead. One place to look, one place to fix, everyone downstream agrees.

Missing either file is not fatal -- current_of() falls back to the row's own
values and the caller decides whether to say so, matching the old behaviour
rather than a hard stop.
"""

import json
import os

_HERE = os.path.dirname(os.path.abspath(__file__))
_MAP_FILE = os.path.join(_HERE, "ftd-channels", "affiliate-map.json")
_OVR_FILE = os.path.join(_HERE, "affiliate-overrides.json")


def _load_map():
    if not os.path.exists(_MAP_FILE):
        return {}
    with open(_MAP_FILE, encoding="utf-8") as fh:
        return json.load(fh).get("map", {})


def _load_overrides():
    if not os.path.exists(_OVR_FILE):
        return {}
    with open(_OVR_FILE, encoding="utf-8") as fh:
        return json.load(fh).get("overrides", {})


AFF_MAP = _load_map()
AFF_OVR = _load_overrides()

MAP_LOADED = bool(AFF_MAP)          # callers that want to log/warn on a miss
OVERRIDES_LOADED = len(AFF_OVR)


def current_of(aff_username, aff_type, aff_source):
    """Today's (aff_type, aff_source) for an affiliate, whatever the cached
    row passed in says. Falls back to that row's own values for an affiliate
    absent from the map (too new for the last refresh, or the file is
    missing) so a lookup miss degrades to the old per-row behaviour rather
    than erasing the affiliate."""
    key = (aff_username or "").strip().lower()
    m = AFF_MAP.get(key)
    at, src = (m["aff_type"], m["aff_source"]) if m else (aff_type, aff_source)
    o = AFF_OVR.get(key)
    if o:
        at = o.get("aff_type", at)
        src = o.get("aff_source", src)
    return at, src
