"use strict";
/**
 * affiliate-channel.js — today's aff_type/aff_source for an affiliate,
 * whatever a given cached row happens to say.
 *
 *   const { currentOf } = require("./affiliate-channel");
 *
 * aff_type/aff_source are CURRENT properties of the affiliate, but every
 * cached row froze whatever they said the day that month was pulled. A
 * re-categorisation at the source never reaches history this way:
 * GetBlue2024 was re-tagged SEO -> Retargeting in 2025, and without this, a
 * cache read SEO for every month before that and Retargeting after — the
 * same affiliate landing on both sides of every year-on-year comparison
 * depending only on which month a row happened to come from.
 *
 * Two files fix that, and are deliberately kept separate:
 *
 *   ftd-channels/affiliate-map.json   a wholesale snapshot of
 *                                     bi.players_info_mv for all ~1,300
 *                                     affiliates, regenerated by the query in
 *                                     ftd-channels/build_ftd_channels.py's own
 *                                     header. Anything hand-edited into it is
 *                                     destroyed on the next refresh.
 *
 *   affiliate-overrides.json          hand-maintained corrections for
 *                                     affiliates we know are mis-tagged AT
 *                                     SOURCE (the map is a faithful snapshot,
 *                                     which means it is also faithful to the
 *                                     source's mistakes). Layered on top of
 *                                     the snapshot, survives a refresh. See
 *                                     that file's own header.
 *
 * This is the JS counterpart of affiliate_channel.py — the Python builders
 * and the JS ones (month-aggregate.js and friends) both need this lookup,
 * and duplicating it a third time is exactly the "nine copies of one rule"
 * problem carveout.py / data-exclusions.js already solved once for the
 * whale-exclusion list. One place to look, one place to fix.
 *
 * A missing file is not fatal — currentOf() falls back to the row's own
 * values, matching the old per-row behaviour rather than a hard stop.
 */

const fs = require("fs");
const path = require("path");

function loadJson(file, key) {
  try {
    const parsed = JSON.parse(fs.readFileSync(file, "utf8"));
    return (parsed && parsed[key]) || {};
  } catch (e) {
    return {};
  }
}

const AFF_MAP = loadJson(path.join(__dirname, "ftd-channels", "affiliate-map.json"), "map");
const AFF_OVR = loadJson(path.join(__dirname, "affiliate-overrides.json"), "overrides");

const MAP_LOADED = Object.keys(AFF_MAP).length > 0;
const OVERRIDES_LOADED = Object.keys(AFF_OVR).length;

/**
 * Today's { affType, affSource } for an affiliate, whatever the cached row
 * passed in says. Falls back to that row's own values for an affiliate
 * absent from the map (too new for the last refresh, or the file is
 * missing) so a lookup miss degrades to the old per-row behaviour rather
 * than erasing the affiliate.
 */
function currentOf(affUsername, affType, affSource) {
  const key = String(affUsername || "").trim().toLowerCase();
  const m = key ? AFF_MAP[key] : null;
  let at = m ? m.aff_type : affType;
  let src = m ? m.aff_source : affSource;
  const o = key ? AFF_OVR[key] : null;
  if (o) {
    if (o.aff_type !== undefined) at = o.aff_type;
    if (o.aff_source !== undefined) src = o.aff_source;
  }
  return { affType: at, affSource: src };
}

module.exports = { currentOf, AFF_MAP, AFF_OVR, MAP_LOADED, OVERRIDES_LOADED };
